# Generated by Django 3.1.3 on 2020-12-08 10:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vkusnooo_auth', '0002_auto_20201206_1701'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Meat Meals', 'Meat Meals'), ('Pasta and Dough', 'Pasta and Dough'), ('Meatless Meals', 'Meatless Meals'), ('Healthy and Dietetic', 'Healthy and Dietetic'), ('Vegan', 'Vegan'), ('Desserts', 'Desserts'), ('Other', 'Other')], default='', max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('ingredients', models.CharField(max_length=10000)),
                ('photo', models.ImageField(blank=True, upload_to='pictures')),
                ('video', models.ImageField(blank=True, upload_to='videos')),
                ('time', models.IntegerField()),
                ('created_by', models.ForeignKey(blank=True, default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=2)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkusnooo_app.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkusnooo_app.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkusnooo_auth.userprofile')),
            ],
        ),
    ]
