# Generated by Django 3.1.3 on 2020-11-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Meat Meals', 'Meat Meals'), ('Pasta and Dough', 'Pasta and Dough'), ('Meatless Meals', 'Meatless Meals'), ('Healthy and Dietetic', 'Healthy and Dietetic'), ('Vegan', 'Vegan'), ('Desserts', 'Desserts'), ('Other', 'Other')], default='', max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('ingredients', models.CharField(max_length=250)),
                ('photo', models.ImageField(upload_to='pictures')),
                ('video', models.ImageField(upload_to='videos')),
                ('time', models.IntegerField()),
            ],
        ),
    ]
