# Generated by Django 3.1.3 on 2020-12-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkusnooo_app', '0003_auto_20201212_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.ImageField(blank=True, upload_to='static/media/videos'),
        ),
    ]
