# Generated by Django 3.1.3 on 2020-12-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkusnooo_app', '0004_auto_20201126_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='type',
            field=models.CharField(choices=[('Meat Meals', 'Meat Meals'), ('Pasta and Dough', 'Pasta and Dough'), ('Meatless Meals', 'Meatless Meals'), ('Healthy and Dietetic', 'Healthy and Dietetic'), ('Vegan', 'Vegan'), ('Desserts', 'Desserts'), ('Other', 'Other')], default='', max_length=100),
        ),
    ]
