# Generated by Django 3.1.3 on 2020-12-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkusnooo_app', '0005_auto_20201213_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='video',
            field=models.FileField(blank=True, upload_to='videos'),
        ),
    ]
