# Generated by Django 3.1.3 on 2020-12-07 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vkusnooo_app', '0008_auto_20201206_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='test',
        ),
        migrations.AddField(
            model_name='like',
            name='value',
            field=models.CharField(choices=[('Like', 'Like'), ('Dislike', 'Dislike')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
