# Generated by Django 3.1.3 on 2020-12-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkusnooo_auth', '0002_auto_20201206_1701'),
        ('vkusnooo_app', '0009_auto_20201207_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vkusnooo_auth.userprofile'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to='vkusnooo_auth.UserProfile'),
        ),
    ]
