# Generated by Django 3.1.3 on 2020-12-07 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkusnooo_app', '0010_auto_20201207_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='created_by',
            new_name='user',
        ),
    ]
