# Generated by Django 3.1.3 on 2020-12-07 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vkusnooo_app', '0011_auto_20201207_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='liked',
        ),
    ]
