# Generated by Django 3.1.3 on 2020-12-07 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vkusnooo_auth', '0002_auto_20201206_1701'),
        ('vkusnooo_app', '0012_auto_20201207_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vkusnooo_auth.userprofile'),
        ),
    ]
