# Generated by Django 3.1.3 on 2020-12-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vkusnooo_auth', '0002_auto_20201206_1701'),
        ('vkusnooo_app', '0015_auto_20201207_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to='vkusnooo_auth.UserProfile'),
        ),
    ]
