# Generated by Django 3.1.3 on 2020-12-08 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vkusnooo_auth', '0003_auto_20201209_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
